version: '2'
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_database
    # MySQL8から新しい認証方式が採用されたがプログラムから接続しようとするとエラーになる
    # 旧来の認証方式に戻すため　--default-authentication-plugin=mysql_native_password
    # 残りはDBの文字コードの設定
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - /vagrant/mysql/init:/docker-entrypoint-initdb.d # 自動実行してほしいファイルを置いておく
      # 1_XXXX, 2_XXXX, ... の順に実行される
  server:
    image: php:7.3-apache # Apacheを含んだPHPイメージ
    container_name: php
    working_dir: /home/app/server
    ports:
      - 80:80 # 80がPHPのデフォルトポート
    volumes:
      - /vagrant/server:/home/app/server
      - /vagrant/client/public:/var/www/html
    depends_on:
      - db
